services:
  - type: web
    name: skducky-ai
    env: python
    runtime: python-3.12.0
    buildCommand: |
      pip install --upgrade pip && 
      pip install -r requirements.txt &&
      curl -fsSL https://ollama.ai/install.sh | sh &&
      chmod +x start_with_ollama.sh
    startCommand: ./start_with_ollama.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: OLLAMA_ENABLED
        value: true
      - key: OLLAMA_URL
        value: http://127.0.0.1:11434
      - key: PYTHONPATH
        value: .
      - key: PORT
        value: 10000
