services:
  - type: web
    name: skducky-ai
    env: python
    runtime: python-3.12.0
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: gunicorn main:app -w 1 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: OLLAMA_ENABLED
        value: false
      - key: PYTHONPATH
        value: .
      - key: PORT
        value: 10000
