services:
  - type: web
    name: skducky-ai
    env: python
    runtime: python-3.12.0
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: uvicorn main:app --host=0.0.0.0 --port=$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: OLLAMA_ENABLED
        value: false
      - key: PYTHONPATH
        value: .
